services:

  smoke:
    build: .
    container_name: smoke-tests

    command: >
      npx playwright test tests/smoke --reporter=html

    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/reports/smoke

    volumes:
      - ./reports/smoke:/app/reports/smoke


  regression:
    build: .
    container_name: regression-tests

    command: >
      npx playwright test tests/regression --reporter=html

    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/reports/regression

    volumes:
      - ./reports/regression:/app/reports/regression


  api:
    build: .
    container_name: api-tests

    command: >
      npx playwright test tests/api --reporter=html

    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/reports/api

    volumes:
      - ./reports/api:/app/reports/api