services:

  smoke:
    build: .
    container_name: smoke-tests

    command: >
      command: npx playwright test tests/smoke

    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/reports/smoke

    volumes:
      - ./reports/smoke:/app/reports/smoke
      - ./allure-results:/app/allure-results


  regression:
    build: .
    container_name: regression-tests

    command: >
      npx playwright test tests/regression

    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/reports/regression

    volumes:
      - ./reports/regression:/app/reports/regression
      - ./allure-results:/app/allure-results

  api:
    build: .
    container_name: api-tests

    command: >
      npx playwright test tests/api
    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/reports/api

    volumes:
      - ./reports/api:/app/reports/api
      - ./allure-results:/app/allure-results