version: '3'

services:

  smoke:
    build: .
    container_name: smoke-tests
    command: npx playwright test tests/smoke

  regression:
    build: .
    container_name: regression-tests
    command: npx playwright test tests/regression

  api:
    build: .
    container_name: api-tests
    command: npx playwright test tests/api